spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres?user=postgres.lqamfnkcnbqkbqldnyly&password=7AyS2puWbTd8iRz8

    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: danieljh7759@gmail.com
    password: bljyyfswyfhjsiia
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

application:
  security:
    jwt:
      secret-key: a4ccf552ca2ee75b2f47068459837e67198c0a038210e9e96dae7dc0aee2091f
      expiration: 864000000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  cors:
    origins: http://localhost:4200,http://localhost:8080,
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088
