spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

application:
  security:
    jwt:
      secret-key: a4ccf552ca2ee75b2f47068459837e67198c0a038210e9e96dae7dc0aee2091f
      expiration: 864000000
  mailing:
    frontend:
      activation-url: ${MAILING_FRONTEND_ACTIVATION_URL}
  cors:
    origins: http://localhost:4200,http://localhost:8080,https://book-social-ui.vercel.app/
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088
